# Generated by Django 5.2.6 on 2025-11-27 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobacion_requerida_monto', models.DecimalField(decimal_places=2, default=50000.0, help_text='Monto mínimo para requerir aprobación', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('proveedor_requerido', models.BooleanField(default=True, help_text='Requerir proveedor al registrar compra')),
                ('dias_alerta_pago', models.IntegerField(default=7, help_text='Días antes del vencimiento para alertar pago pendiente', validators=[django.core.validators.MinValueValidator(1)])),
                ('permitir_compra_producto_inactivo', models.BooleanField(default=False, help_text='Permitir comprar productos marcados como inactivos')),
            ],
            options={
                'verbose_name': 'Configuración de Compras',
                'verbose_name_plural': 'Configuración de Compras',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_minimo_alerta', models.IntegerField(default=10, help_text='Cantidad mínima de productos antes de alertar', validators=[django.core.validators.MinValueValidator(0)])),
                ('dias_alerta_vencimiento', models.IntegerField(default=30, help_text='Días antes del vencimiento para mostrar alerta', validators=[django.core.validators.MinValueValidator(1)])),
                ('permitir_stock_negativo', models.BooleanField(default=False, help_text='Permitir ventas cuando no hay stock suficiente')),
                ('actualizar_precios_automatico', models.BooleanField(default=False, help_text='Actualizar precios de venta automáticamente según costo + margen')),
                ('margen_ganancia_default', models.DecimalField(decimal_places=2, default=30.0, help_text='Margen de ganancia por defecto (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Configuración de Inventario',
                'verbose_name_plural': 'Configuración de Inventario',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionNotificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificar_stock_bajo', models.BooleanField(default=True, help_text='Notificar cuando el stock esté bajo')),
                ('notificar_productos_vencidos', models.BooleanField(default=True, help_text='Notificar productos próximos a vencer')),
                ('notificar_pagos_pendientes', models.BooleanField(default=True, help_text='Notificar pagos pendientes a proveedores')),
                ('notificar_creditos_vencidos', models.BooleanField(default=True, help_text='Notificar créditos de clientes vencidos')),
                ('notificar_nueva_venta', models.BooleanField(default=False, help_text='Notificar cada nueva venta registrada')),
                ('notificar_cierre_caja', models.BooleanField(default=True, help_text='Notificar al cerrar caja con diferencias')),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuración de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionReportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_reporte_default', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='mensual', help_text='Período por defecto para generar reportes', max_length=10)),
                ('incluir_graficos', models.BooleanField(default=True, help_text='Incluir gráficos en reportes exportados')),
                ('top_productos_count', models.IntegerField(default=10, help_text="Cantidad de productos a mostrar en 'Top Productos'", validators=[django.core.validators.MinValueValidator(1)])),
                ('enviar_reporte_email', models.BooleanField(default=False, help_text='Enviar reporte automático por email')),
                ('email_destinatarios', models.TextField(blank=True, help_text='Emails separados por comas para envío de reportes')),
            ],
            options={
                'verbose_name': 'Configuración de Reportes',
                'verbose_name_plural': 'Configuración de Reportes',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Pchela Belén', help_text='Nombre de la empresa', max_length=200)),
                ('rut_empresa', models.CharField(blank=True, help_text='RUT/NIT de la empresa', max_length=20)),
                ('direccion', models.CharField(blank=True, help_text='Dirección de la empresa', max_length=300)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=50)),
                ('email_contacto', models.EmailField(blank=True, help_text='Email de contacto', max_length=254)),
                ('moneda', models.CharField(default='ARS', help_text='Código de moneda (ARS, USD, etc.)', max_length=3)),
                ('zona_horaria', models.CharField(default='America/Argentina/Buenos_Aires', help_text='Zona horaria del sistema', max_length=50)),
                ('formato_fecha', models.CharField(default='DD/MM/YYYY', help_text='Formato de visualización de fechas', max_length=20)),
                ('idioma', models.CharField(default='es', help_text='Idioma del sistema', max_length=5)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento_maximo', models.DecimalField(decimal_places=2, default=20.0, help_text='Descuento máximo permitido (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('permitir_ventas_credito', models.BooleanField(default=True, help_text='Permitir ventas a crédito')),
                ('limite_credito_default', models.DecimalField(decimal_places=2, default=10000.0, help_text='Límite de crédito por defecto para nuevos clientes', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('dias_credito_default', models.IntegerField(default=30, help_text='Días de crédito por defecto', validators=[django.core.validators.MinValueValidator(1)])),
                ('comision_tarjeta', models.DecimalField(decimal_places=2, default=3.0, help_text='Comisión por pago con tarjeta (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('permitir_precios_personalizados', models.BooleanField(default=False, help_text='Permitir modificar precios durante la venta')),
            ],
            options={
                'verbose_name': 'Configuración de Ventas',
                'verbose_name_plural': 'Configuración de Ventas',
            },
        ),
    ]
