# Generated by Django 5.2.6 on 2025-11-27 04:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionventas',
            name='comision_tarjeta',
        ),
        migrations.AlterField(
            model_name='configuracionventas',
            name='limite_credito_default',
            field=models.DecimalField(decimal_places=2, default=10000.0, help_text='Límite de cuenta corriente por defecto para nuevos clientes', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='configuracionventas',
            name='permitir_ventas_credito',
            field=models.BooleanField(default=True, help_text='Permitir ventas a crédito (cuenta corriente)'),
        ),
    ]
