# Generated by Django 5.2.6 on 2025-11-27 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisosEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_ventas', models.BooleanField(default=True, help_text='Permite acceder al módulo de ventas y realizar operaciones de venta', verbose_name='Acceso a Ventas')),
                ('puede_productos', models.BooleanField(default=False, help_text='Permite ver y gestionar el catálogo de productos', verbose_name='Acceso a Productos')),
                ('puede_clientes', models.BooleanField(default=False, help_text='Permite ver y gestionar información de clientes', verbose_name='Acceso a Clientes')),
                ('puede_compras', models.BooleanField(default=False, help_text='Permite gestionar compras a proveedores', verbose_name='Acceso a Compras')),
                ('puede_proveedores', models.BooleanField(default=False, help_text='Permite ver y gestionar proveedores', verbose_name='Acceso a Proveedores')),
                ('puede_lotes', models.BooleanField(default=False, help_text='Permite gestionar lotes de productos', verbose_name='Acceso a Lotes')),
                ('puede_marcas', models.BooleanField(default=False, help_text='Permite gestionar marcas de productos', verbose_name='Acceso a Marcas')),
                ('puede_reportes', models.BooleanField(default=False, help_text='Permite ver reportes y estadísticas del negocio', verbose_name='Acceso a Reportes')),
                ('puede_movimientos_caja', models.BooleanField(default=False, help_text='Permite ver y registrar movimientos de caja', verbose_name='Acceso a Movimientos de Caja')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_empleado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso de Empleado',
                'verbose_name_plural': 'Permisos de Empleados',
                'ordering': ['user__username'],
            },
        ),
    ]
